### PR TITLE
Repository quality improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
Overall, I'm hoping these changes make it so that the codebase and repository is now much nicer to look at.

### CODE REVIEW

**Comment by dzmanto** [comment]
> Overall, I'm hoping these changes make it so that the codebase and repository is now much nicer to look at.

Thank you Taco. I actually made some minor modifications to DSPTask, cf the annexed code.
[DSPTask.java.gz](https://github.com/dzmanto/foehnix/files/5712196/DSPTask.java.gz)

**Comment by dzmanto** [comment]
Largely implemented the changes brought forward by TacoTheDank. Thank you.

**Comment by TacoTheDank** [comment]
@dzmanto Happy to help!

**Comment by dzmanto** [comment]
Thank you so much and merry Christmas!

Cheers,

Daniela

________________________________

**Comment by TacoTheDank** [comment]
You too! :)

**Pull request closed without merging**
